from format_readers.bin_reader import BINReader
from format_readers.bmp_reader import BMPReader
from format_readers.csv_reader import CSVReader
from format_readers.html_reader import HTMLReader
from format_readers.ics_reader import ICSReader
from format_readers.ini_reader import INIReader
from format_readers.json_reader import JSONReader
from format_readers.jsonl_reader import JSONLReader
from format_readers.md_reader import MDReader
from format_readers.pls_reader import PLSReader
from format_readers.psv_reader import PSVReader
from format_readers.ssv_reader import SSVReader
from format_readers.svg_reader import SVGReader
from format_readers.tsv_reader import TSVReader
from format_readers.txt_reader import TXTReader
from format_readers.vcf_reader import VCFReader
from format_readers.wav_reader import WAVReader
from format_readers.xml_reader import XMLReader
from format_readers.xpm_reader import XPMReader